export * from './users.repository';
export * from './user-credentials.repository';
export * from './movies.repository';
export * from './actors.repository';
export * from './reviews.repository';
export * from './links.repository';
export * from './rates.repository';
export * from './categories.repository';
export * from './movie-actor.repository';
